### ISSUE TITLE
Issue when saving to PDF in windows

### ISSUE THREAD

**Issue by cowboy** [joshbduncan/word-search-generator#80]
Hi, I'm running Windows 11, and am running into an issue when saving as PDF. I'm running 3.5.2, installed via pip. Python is 3.12.5.

When I specify a filename, it works:

```
C:\Users\Cowboy\Documents>word-search --random 20 -s 20 -f pdf -o "file 1.pdf"
Puzzle saved: C:\Users\Cowboy\Documents\file 1.pdf
```

When I don't, it fails like so:

```
C:\Users\Cowboy\Documents>word-search --random 20 -s 20 -f pdf
Traceback (most recent call last):
  File "C:\Users\Cowboy\AppData\Local\Programs\Python\Python312\Lib\site-packages\word_search_generator\export.py", line 117, in write_pdf_file
    pdf.output(path)
  File "C:\Users\Cowboy\AppData\Local\Programs\Python\Python312\Lib\site-packages\fpdf\fpdf.py", line 2348, in output
    name.write_bytes(self.buffer)
  File "C:\Users\Cowboy\AppData\Local\Programs\Python\Python312\Lib\pathlib.py", line 1036, in write_bytes
    with self.open(mode='wb') as f:
         ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cowboy\AppData\Local\Programs\Python\Python312\Lib\pathlib.py", line 1013, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: 'WordSearchPuzzle 2024-12-16 10:37:49.163347.pdf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Cowboy\AppData\Local\Programs\Python\Python312\Scripts\word-search.exe\__main__.py", line 7, in <module>
  File "C:\Users\Cowboy\AppData\Local\Programs\Python\Python312\Lib\site-packages\word_search_generator\cli.py", line 249, in main
    foutput = puzzle.save(path=path, format=format, solution=args.cheat)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cowboy\AppData\Local\Programs\Python\Python312\Lib\site-packages\word_search_generator\__init__.py", line 410, in save
    saved_file = export.write_pdf_file(path, self, solution)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cowboy\AppData\Local\Programs\Python\Python312\Lib\site-packages\word_search_generator\export.py", line 119, in write_pdf_file
    raise OSError(f"File could not be saved to '{path}'.")
OSError: File could not be saved to 'WordSearchPuzzle 2024-12-16 10:37:49.163347.pdf'.
```

**Comment by joshbduncan** [comment]
So, as you may have noticed, the package generates a timestamp file name if you don't provide one. I just noticed that the timestamp includes colons which are prohibited on Windows so that is what causes the error. I will get this fixed and pushed to GitHub. Thanks!
